json.id application.id
json.user_id application.user_id
json.tattooer_id application.tattooer_id
json.amount application.amount
json.number_of_months application.number_of_months
json.date_of_appt application.date_of_appt
json.approved application.approved
json.description application.description
json.created_at application.created_at
json.updated_at application.updated_at