json.id tattooer.id
json.last_name tattooer.last_name
json.first_name tattooer.first_name
json.email tattooer.email
json.user_name tattooer.user_name
json.address tattooer.address
json.phone_number tattooer.phone_number
json.tattoo_shop tattooer.tattoo_shop
json.created_at tattooer.created_at
json.updated_at tattooer.updated_at
